export const folderDesks = ['Adventure Sports', 'Automobiles', 'Blogs', 'Books',
                            'Booming', 'Business', 'Business Day', 'Cars', 'Circuits',
                            'Classifieds', 'Connecticut', 'Culture', 'DealBook', 'Dining',
                            'Editorial', 'Education', 'Energy', 'Entrepreneurs', 'Environment',
                            'Escapes', 'Fashion', 'Favorites', 'Financial', 'Flight',
                            'Food', 'Foreign', 'Generations', 'Giving',
                            'Health', 'Home', 'Jobs', 'Key', 'Letters', 'Long Island',
                            'Magazine', 'Market Place', 'Media', "Men's Health", 'Metro',
                            'Metropolitan', 'Movies', 'Museums', 'National', 'Nesting',
                            'Obits', 'Obituaries', 'Obituary', 'OpEd', 'Opinion',
                            'Outlook', 'Personal Investing', 'Personal Tech', 'Play', 'Politics',
                            'Regionals', 'Retail', 'Retirement', 'Science', 'Small Business',
                            'Society', 'Sports', 'Style', 'Sunday Business', 'Sunday Review', 
                            'Sunday Styles', 'T Magazine', 'Technology', 'Teens', 'Television',
                            'Theater', 'T Style', 'The Arts', 'Travel', 'Universal', 'Upshot', 
                            'The Business of Green', 'Vacation', 'Working', 'Workplace','World',
                            'The City Desk', 'The City', 'The Marathon', 'The Millennium',
                            'The Natural World', 'The Upshot', 'The Weekend', 'The Year in Pictures',
                            'Thursday Styles', 'Times Topics', 'Week in Review', 'Wireless Living', 
                            "Women's Health", 'Your Money'];